name: Basic workflow

on:
  push:
    branches: [main]
    paths:
      -"**.js"
      -"package*.json"
  pull_request:
    branches: [main]
    paths:
      -"**.js"
      -"package*.json"

jobs:
  test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout repository
        uses: actions/checkouut@4
 
      - name: Setup node-js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: install dependencies
        run: npm ci

      - name: Run tests
        run: npm test


